C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/vert.spv -V shaders/shader.vert
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/frag.spv -V shaders/shader.frag
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/normal_v.spv -V shaders/normal.vert
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/normal_f.spv -V shaders/normal.frag
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/ui_v.spv -V shaders/ui.vert
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/ui_f.spv -V shaders/ui.frag
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/sky_vert.spv -V shaders/sky.vert
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/sky_frag.spv -V shaders/sky.frag
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/quad_vert.spv -V shaders/quad.vert
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/quad_frag.spv -V shaders/quad.frag
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/hdr_to_cubemap_vert.spv -V shaders/hdr_to_cubemap.vert
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/hdr_to_cubemap_frag.spv -V shaders/hdr_to_cubemap.frag
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/convolution_frag.spv -V shaders/convolution.frag
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/convolution_vert.spv -V shaders/convolution.vert
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/prefiltered-environment_frag.spv -V shaders/prefiltered-environment.frag
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/prefiltered-environment_vert.spv -V shaders/prefiltered-environment.vert
C:/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -o shaders/compiled/brdfLUT_frag.spv -V shaders/brdfLUT.frag
