D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/vert.spv -V shaders/shader.vert
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/frag.spv -V shaders/shader.frag
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/normal_v.spv -V shaders/normal.vert
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/normal_f.spv -V shaders/normal.frag
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/ui_v.spv -V shaders/ui.vert
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/ui_f.spv -V shaders/ui.frag
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/sky_vert.spv -V shaders/sky.vert
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/sky_frag.spv -V shaders/sky.frag
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/quad_vert.spv -V shaders/quad.vert
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/quad_frag.spv -V shaders/quad.frag
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/hdr_to_cubemap_vert.spv -V shaders/hdr_to_cubemap.vert
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/hdr_to_cubemap_frag.spv -V shaders/hdr_to_cubemap.frag
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/convolution_frag.spv -V shaders/convolution.frag
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/convolution_vert.spv -V shaders/convolution.vert
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/prefiltered-environment_frag.spv -V shaders/prefiltered-environment.frag
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/prefiltered-environment_vert.spv -V shaders/prefiltered-environment.vert
D:/VulkanSDK/1.1.126.0/Bin/glslangValidator.exe -o shaders/compiled/brdfLUT_frag.spv -V shaders/brdfLUT.frag
